version: 0.0
os: linux
# S3에 있는 zip 파일이 EC2에 배포될 위치를 지정
  
files:
  - source: / # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 루트로 지정 (전체 파일)
    destination: /home/ubuntu/app/JuJuAssembly # source에서 지정된 파일을 받을 위치, 이후 jar를 실행하는 등은 destination에서 옮긴 파일들로 진행
    overwrite: yes
    
permissions: # CodeDeploy에서 EC2서버로 넘겨준 파일들을 모두 ubuntu권한을 갖도록 합니다.
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    
hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60

  ApplicationStart:
    - location: start.sh
      timeout: 60
